### ISSUE TITLE
Bot crashes in SSCAIT and got disabled, please, please fix it if possible

### ISSUE THREAD

**Issue by Ravaelles** [chriscoxe/ZZZKBot#1]
Hey, Chris!

Sorry to bother you, but as I was watching SSCAIT stream transmission and chating with guys, we all agreed that your bot is definitely the best N-pool bot, but it started crashing recently and got disabled. 

Your bot has truly pushed other coders to another level with zerglings defence. I think it'd be just great if you could fix the issue! I also think the entire community would be grateful if you could do it, not just me!

I'm not aware of the error details, just wanted to personally ask you if it was even possible. When you have some free time.

Please consider it and thank you in the name of the **Swarm**! :)
Have a nice day in Down Under!

**Comment by dgant** [comment]
Would love to see ZZZKBot back in action!

**Comment by chriscoxe** [comment]
v1.7.0 now uploaded to SSCAIT.  I also added a config file to SSCAIT (shouldn't exist by default) that contains some example configurations, in case anyone wants to run ZZZKBot in their own environments and control the initial strategy parameter values that ZZZKBot uses against specified opponents.
